# Generated by Django 6.0.1 on 2026-01-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mexicano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Portada',
        ),
    ]
