# Generated by Django 6.0.1 on 2026-01-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mexicano', '0002_comentario_delete_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='clave',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
