# Generated by Django 6.0.1 on 2026-01-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mexicano', '0003_noticia_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='marqueting',
            name='alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
