# Generated by Django 6.0.1 on 2026-01-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mexicano', '0004_marqueting_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duracion',
        ),
        migrations.AddField(
            model_name='foto',
            name='imagen_small',
            field=models.ImageField(default=1, upload_to='imagenes/'),
            preserve_default=False,
        ),
    ]
