# Generated by Django 6.0.1 on 2026-01-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mexicano', '0005_remove_cancion_duracion_remove_video_duracion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarquetingFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=200)),
                ('imagen', models.FileField(upload_to='marketing/imagenes/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarquetingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='marketing/videos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Marqueting',
        ),
    ]
