# Generated by Django 6.0.1 on 2026-01-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mexicano', '0007_resena_delete_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrellas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrella', models.DecimalField(decimal_places=1, max_digits=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
