# Generated by Django 6.0.1 on 2026-01-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mexicano', '0008_estrellas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estrellas',
            name='estrella',
            field=models.FloatField(),
        ),
    ]
