# Generated by Django 6.0.1 on 2026-01-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mexicano', '0009_alter_estrellas_estrella'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estrellas',
            name='fecha',
        ),
    ]
