# Generated by Django 6.0.1 on 2026-01-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mexicano', '0010_remove_estrellas_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estrellas',
            old_name='estrella',
            new_name='calificacion',
        ),
        migrations.AddField(
            model_name='estrellas',
            name='calificacion_aprox',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estrellas',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estrellas',
            name='suma_estrellas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
