# Generated by Django 6.0.1 on 2026-01-31 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mexicano', '0011_rename_estrella_estrellas_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrellas',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estrellas',
            name='imagen',
            field=models.ImageField(default=1, upload_to='calificacion/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estrellas',
            name='titulo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resena',
            name='estrella',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mexicano.estrellas'),
            preserve_default=False,
        ),
    ]
