# Generated by Django 6.0.1 on 2026-01-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mexicano', '0012_estrellas_descripcion_estrellas_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estrellas',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='estrellas',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='estrellas',
            name='titulo',
        ),
    ]
