# Generated by Django 6.0.1 on 2026-01-31 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mexicano', '0013_remove_estrellas_descripcion_remove_estrellas_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estrellas',
            name='suma_estrellas',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='estrella',
        ),
    ]
