# Generated by Django 6.0.1 on 2026-01-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mexicano', '0014_remove_estrellas_suma_estrellas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(choices=[(1, '1 ( basico )'), (2, '2 ( normal )'), (3, '3 ( bueno )'), (4, '4 ( muy bueno )'), (5, '5 ( exelente )')]),
        ),
    ]
